namespace: tofugarden

name: secureboot

version: 0.0.1

readme: README.md

authors:
  Christopher Palmer-Richez tofu.ansible@chorky.net @crichez

description: A collection related to secure boot management.

license:
  - GPL-3.0-only

tags:
  - secureboot
  - mok
  - shim
  - tpm
  - uki

dependencies:
  community.crypto: ">=9.2.0,<10.0.0"
  community.general: ">=2.21.1,<3.0.0"

repository: https://github.com/crichez/tofugarden.secureboot.git

documentation: https://github.com/crichez/tofugarden.secureboot

issues: https://github.com/crichez/tofugarden.secureboot/issues
