- name: Install required packages
  ansible.builtin.dnf:
    name:
      - binutils
      - sbsigntools
      - systemd-boot
      - openssl
  become: true

- name: Create Machine Owner Keys
  become: true
  block:
    - name: Create private key and certificate # noqa inline-env-var
      ansible.builtin.command:
        cmd: openssl
        argv:
          - req
          - -new
          - -x509
          - -newkey
          - rsa:2048
          - -keyout
          - "{{ uki_config_kernel_install_config_root }}/MOK.key"
          - -out
          - "{{ uki_config_kernel_install_config_root }}/MOK.crt"
          - -nodes
          - -days
          - "3650"
          - -subj
          - "/CN={{ uki_config_mok_name }}/"
        creates:
          - "{{ uki_config_kernel_install_config_root }}/MOK.crt"
          - "{{ uki_config_kernel_install_config_root }}/MOK.key"

    - name: Set permissions on certificate
      ansible.builtin.file:
        path: "{{ uki_config_kernel_install_config_root }}/MOK.crt"
        mode: '0600'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

    - name: Set permissions on private key
      ansible.builtin.file:
        path: "{{ uki_config_kernel_install_config_root }}/MOK.key"
        mode: '0600'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

    - name: Derive public certificate # noqa inline-env-var
      ansible.builtin.command:
        cmd: openssl
        argv:
          - x509
          - -in
          - "{{ uki_config_kernel_install_config_root }}/MOK.crt"
          - -out
          - "{{ uki_config_kernel_install_config_root }}/MOK.cer"
          - -outform DER
        creates:
          - "{{ uki_config_kernel_install_config_root }}/MOK.cer"

    - name: Set permissions on public cert
      ansible.builtin.file:
        path: "{{ uki_config_kernel_install_config_root }}/MOK.cer"
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

- name: Import MOK
  become: true
  vars_prompt:
    - name: mok_password
      prompt: 'Enter MOK password'
      unsafe: true
  vars:
    enrolled: "{{ lookup('ansible.builtin.pipe', 'mokutil --list-enrolled') }}"
    new: "{{ lookup('ansible.builtin.pipe', 'mokutil --list-new') }}"
  ansible.builtin.expect:
    command: mokutil --import {{ uki_config_kernel_install_config_root }}/MOK.cer
    responses:
      .*: "{{ mok_password }}"
  register: mok_import
  when:
    - enrolled | ansible.builtin.search(uki_config_mok_name)
    - new | ansible.builtin.search(uki_config_mok_name)
  notify:
    - MokManager warning
    - Reboot prompt

- name: Configure kernel-install to generate UKIs
  become: true
  block:
    - name: Set the install layout to UKI
      community.general.ini_file:
        path: "{{ uki_config_kernel_install_config_root }}/install.conf"
        option: layout
        value: uki
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

    - name: Configure kernel-install to use dracut as the initrd generator
      community.general.ini_file:
        path: "{{ uki_config_kernel_install_config_root }}/install.conf"
        option: initrd_generator
        value: "{{ uki_config_initrd_generator }}"
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

    - name: Configure kernel-install to use dracut as the UKI generator
      community.general.ini_file:
        path: "{{ uki_config_kernel_install_config_root }}/install.conf"
        option: "uki_generator"
        value: "{{ uki_config_uki_generator }}"
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

- name: Configure dracut to sign generated UKIs
  become: true
  block:
    - name: Set signing certificate
      community.general.ini_file:
        path: "{{ uki_config_dracut_conf_dir }}/uki.conf"
        option: uefi_secureboot_cert
        value: "{{ uki_config_kernel_install_config_root }}/MOK.crt"
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t

    - name: Set signing private key
      community.general.ini_file:
        path: "{{ uki_config_dracut_conf_dir }}/uki.conf"
        option: uefi_secureboot_key
        value: "{{ uki_config_kernel_install_config_root }}/MOK.key"
        mode: '0644'
        owner: root
        group: root
        seuser: system_u
        serole: object_r
        setype: etc_t
