argument_specs:
  main:
    short_description: UKI Configuration
    description: Configure kernel-install to build and sign UKIs
    version_added: "0.0.1"
    author: "Christopher Palmer-Richez (tofugarden)"
    options:
      uki_config_mok_setype:
        type: str
        default: cert_t
        description: The SELinux type assigned to MOK certificate files.

      uki_config_initrd_generator:
        type: str
        default: dracut

      uki_config_uki_generator:
        type: dict
        description: The tool used to generate the UKI.
        options:
          ukify:
            type: dict
            description: The options needed by systemd-ukify to sign a UKI.
            options:
              cmdline:
                type: path
                description: The path to the kernel command line.
                default: /etc/kernel/cmdline

              signing_tool:
                type: dict
                description: The tool used to sign the UKI - sbsign.
                options:
                  sbsign:
                    type: dict
                    description: The options needed by sbsign.
                    options:
                      private_key:
                        type: path
                        description: The path to the signing certificate's private key.
                        default: /etc/kernel/MOK.priv

                      certificate:
                        type: path
                        description: The path to the signing certificate.
                        default: /etc/kernel/MOK.cer

                  pesign:
                    type: dict
                    description: A dictionary of options needed by pesign.
                    options:
                      certificate_nickame:
                        type: str
                        required: true
                        description: The nickname of the certificate used to sign UKIs.

                      nss_database:
                        type: path
                        description: The path to the NSS database where the certificate is stored.
                        default: /etc/pki/pesign

      uki_config_kernel_install_config_root:
        type: path
        default: /etc/kernel

      uki_config_dracut_conf_dir:
        type: path
        default: /etc/dracut.conf.d

      uki_config_mok_name:
        type: str
        required: true
