argument_specs:
  main:
    short_description: UKI Configuration
    description: Configure kernel-install to build and sign UKIs
    version_added: "0.0.1"
    author: "Christopher Palmer-Richez (tofugarden)"
    options:
      uki_config_initrd_generator:
        type: str
        choices:
          - dracut
        default: dracut

      uki_config_mok:
        type: dict
        description: |
          Location and information for your MOK.

          Use this option to specify the path where the MOK certificate and
          private key will be stored for UKI signing purposes.
        options:
          private_key:
            type: path
            description: The path to the MOK private key.
            default: /etc/kernel/MOK.priv

          certificate:
            type: path
            description: The path to the MOK x509 certificate.
            default: /etc/kernel/MOK.cer

          owner:
            type: str
            default: root

          group:
            type: str
            default: root

          mode:
            type: str
            default: "0600"

          selevel:
            type: str
            default: s0

          seuser:
            type: str
            default: system_u

          serole:
            type: str
            default: object_r

          setype:
            type: str
            default: cert_t

      uki_config_cmdline:
        type: path
        description: The path to the kernel command line.
        default: /etc/kernel/cmdline

      uki_config_kernel_install_config_root:
        type: path
        default: /etc/kernel
