- name: MokManager warning
  ansible.builtin.debug:
    msg: |
      A new Machine Owner Key (MOK) was enrolled. Before this playbook can
      continue, the import will need to be manually validated in a program
      called MokManager. This will happen automatically when the machine is
      rebooted, but requires an administrator with access to a local console.

      MokManager is very easy to use. Once in the menu select "Enroll MOK,"
      enter the same password you just provided, and reboot. This playbook
      will resume when the host is back online, or will automatically fail
      after ten minutes. If something strange happens, just run the play
      again.

- name: Reboot prompt
  ansible.builtin.pause:
    prompt: Ready to reboot? (y/n)
    echo: false
  register: reboot_prompt
  changed_when: reboot_prompt == 'y' or reboot_prompt == 'Y'
  failed_when: reboot_prompt != 'y' or reboot_prompt != 'Y'
  notify:
    - Reboot

- name: Reboot
  ansible.builtin.reboot:
  become: true
