uki_config_initrd_generator: dracut
uki_config_uki_generator: ukify
uki_config_mok:
  private_key: /etc/kernel/MOK.priv
  certificate: /etc/kernel/MOK.cer
  owner: root
  group: root
  mode: "0600"
  seuser: system_u
  serole: object_r
  setype: cert_t
  selevel: s0

uki_config_cmdline: /etc/kernel/cmdline
uki_config_kernel_install_config_root: /etc/kernel
uki_config_dracut_conf_dir: /etc/dracut.conf.d
