name: ansible-lint
on:
  pull_request:
    branches:
      - main
      - release/v*

  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        run: ansible-lint 
