name: ansible-lint
on:
  pull_request:
    branches:
      - main
      - release/v*

  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run ansible-lint
        run: ansible-lint
