name: ansible-lint
on:
  pull_request:
    branches:
      - main
      - release/v*

  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install collections
        run: ansible-galaxy collection install community.crypto community.general
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
