name: publish
on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish to Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Get expected version string
        shell: echo "VERSION={$GITHUB_REF_NAME:1}" >> "$GITHUB_ENV"

      - name: Publish to Galaxy
        run: |
          ansible-galaxy collection publish \
          tofugarden-secureboot-${{ env.VERSION }}.tar.gz \
          --token ${{ secrets.GALAXY_API_KEY }}
