---
- name: Deploy collection to galaxy
  on:
    release:
      types:
        - released

  jobs:
    publish:
      name: Publish to Galaxy
      runs-on: ubuntu-latest
      steps:
        - uses: checkout@v4
          with:
            ref: ${{ github.ref }}

        - name: Build collection
          run: ansible-galaxy collection build

        - name: Get expected version string
          shell: VERSION=$(echo ${{ github.ref_name }} | sed -e 's/v\(.*\)/\1/'

        - name: Publish to Galaxy
          run: |
            ansible-galaxy collection publish \
            tofugarden-secureboot-$VERSION.tar.gz \
            --token ${{ secrets.GALAXY_API_KEY }}
