name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install antsibull-changelog
        run: pip install antsibull-changelog

      - name: Generate changelog
        run: antsibull-changelog release

      - name: Build collection tarball
        run: ansible-galaxy collection build

      - name: Get version string
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> "$GITHUB_ENV"

      - uses: ncipollo/release-action@v1
        with:
          artifacts:
            - crichez-secureboot-${{ env.VERSION }}.tar.gz
          body_file: CHANGELOG.md
